# Generated by Django 4.0.7 on 2022-10-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='day',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='day_visits',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_visits',
        ),
    ]
