# Generated by Django 4.0.7 on 2022-11-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_like_post_alter_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='likes',
        ),
    ]
