# Generated by Django 4.0.7 on 2022-11-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_liked_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked',
        ),
    ]
