# Generated by Django 4.0.7 on 2022-11-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_likes_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
