# Generated by Django 4.0.7 on 2022-11-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_like_post_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
    ]
