# Generated by Django 4.1.3 on 2022-11-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_post_is_deleted'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
