# Generated by Django 4.1.3 on 2022-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('NOT_MODERATED', 'На модерацию'), ('VALID', 'Опубликовано'), ('INVALID', 'Отклонено'), ('ON_REMOVAL', 'На удалении')], default='NOT_MODERATED', max_length=100, verbose_name='Статус модерации'),
        ),
    ]
